In [1]:
import numpy as np
import pandas as pd
import statistics
from pandas.plotting import autocorrelation_plot
from statsmodels.graphics.tsaplots import plot_pacf
from matplotlib import pyplot
from statsmodels.tsa.arima_model import ARIMA 
from sklearn.metrics import mean_squared_error

In [2]:
#read file
df_data = pd.read_csv("data/dataset_mood_smartphone.csv")

In [3]:
prev_day="02-26"
new_data=pd.DataFrame(columns=['id', 'time', 'var',"value"])
temp_list=[]
for index, row in df_data.iterrows():
    date=row["time"].split(" ")[0]
    date=date.split("-")[1]+"-"+date.split("-")[2]
    if date != prev_day:
        new_data.loc[index]=[df_data.loc[index-1]["id"], prev_day , df_data.loc[index-1]["variable"], statistics.mean(temp_list)]
        temp_list=[row["value"]]
    else:
        temp_list.append(row["value"])
    prev_day=date

In [8]:
new_data

             id   time             var       value
4       AS14.01  02-26            mood    6.250000
7       AS14.01  02-27            mood    6.333333
12      AS14.01  03-21            mood    6.200000
17      AS14.01  03-22            mood    6.400000
22      AS14.01  03-23            mood    6.800000
27      AS14.01  03-24            mood    6.000000
31      AS14.01  03-25            mood    6.750000
36      AS14.01  03-26            mood    6.600000
41      AS14.01  03-27            mood    7.000000
46      AS14.01  03-28            mood    6.400000
51      AS14.01  03-29            mood    8.000000
55      AS14.01  03-30            mood    7.500000
60      AS14.01  03-31            mood    7.400000
65      AS14.01  04-01            mood    6.000000
69      AS14.01  04-02            mood    6.500000
74      AS14.01  04-03            mood    6.400000
79      AS14.01  04-04            mood    6.200000
84      AS14.01  04-05            mood    6.800000
88      AS14.01  04-06            mood    6.500000
92      AS14.01  04-07            mood    6.500000
97      AS14.01  04-08            mood    6.600000
102     AS14.01  04-09            mood    7.400000
107     AS14.01  04-10            mood    7.400000
112     AS14.01  04-11            mood    7.000000
116     AS14.01  04-12            mood    7.250000
120     AS14.01  04-13            mood    8.000000
125     AS14.01  04-14            mood    7.200000
130     AS14.01  04-15            mood    6.400000
135     AS14.01  04-16            mood    7.200000
140     AS14.01  04-17            mood    6.600000
...         ...    ...             ...         ...
376848  AS14.28  04-12  appCat.weather   14.090333
376850  AS14.28  04-13  appCat.weather   53.429500
376852  AS14.28  04-14  appCat.weather   33.129000
376853  AS14.28  04-15  appCat.weather   43.824000
376855  AS14.28  04-16  appCat.weather   39.618000
376857  AS14.28  04-18  appCat.weather   35.589000
376859  AS14.28  04-19  appCat.weather   11.094000
376860  AS14.28  04-21  appCat.weather   39.010000
376863  AS14.28  04-22  appCat.weather   14.918667
376865  AS14.28  04-23  appCat.weather   26.720000
376869  AS14.28  04-24  appCat.weather   32.641250
376873  AS14.28  04-25  appCat.weather   15.677500
376878  AS14.28  04-26  appCat.weather   20.911400
376887  AS14.28  04-27  appCat.weather   18.930222
376888  AS14.28  05-01  appCat.weather   40.242000
376889  AS14.28  05-03  appCat.weather   43.930000
376891  AS14.28  05-04  appCat.weather   15.042000
376893  AS14.28  05-05  appCat.weather   26.735000
376894  AS14.28  05-06  appCat.weather   31.711000
376896  AS14.28  05-07  appCat.weather    4.593000
376898  AS14.30  03-23  appCat.weather  183.468500
376899  AS14.30  03-24  appCat.weather   15.070000
376900  AS14.30  03-26  appCat.weather    6.087000
376901  AS14.30  03-30  appCat.weather    1.007000
376904  AS14.30  04-06  appCat.weather   32.501667
376907  AS14.30  04-07  appCat.weather   24.962000
376908  AS14.30  04-11  appCat.weather    8.032000
376909  AS14.30  04-19  appCat.weather    3.008000
376910  AS14.30  04-26  appCat.weather    7.026000
376911  AS14.30  04-27  appCat.weather   23.033000

[15518 rows x 4 columns]

In [44]:
df_mood_id = new_data.loc[(new_data['var'] == "mood")]  #& (new_data['id'] == "AS14.01")
#df_mood_id = new_data.loc[new_data['var'] == "mood"]
df_time_value = df_mood_id[['time',"value"]].reset_index()
df_time_value['time'] = pd.to_datetime(df_time_value['time'],format="%m-%d")

index_list = []
for i, row in df_time_value.iterrows():
    index_list.append(i)
    index_list = index_list[-3:]
    if len(index_list) == 3:
        delta1 = (df_time_value['time'].iloc[index_list[0]] - df_time_value['time'].iloc[index_list[1]]).days
        delta2 = (df_time_value['time'].iloc[index_list[1]] - df_time_value['time'].iloc[index_list[2]]).days
        delta = delta1 + delta2
        if delta < -2:
            print(delta)

#Set up the input for ARIMA
# index = df_time_value[["time"]].values
# data_np = df_time_value["value"].values
# series = pd.Series(data_np, index=index)
# X= series.values

-23
-23
-3
-3
-3
-13
-3
-3
-4
-4
-3
-3
-3
-3
-8
-8
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-3
-4
-5
-3
-3
-3
-3
-3
-4
-4
-3
-3

In [15]:
df_time_value

      time     value
4    02-26  6.250000
7    02-27  6.333333
12   03-21  6.200000
17   03-22  6.400000
22   03-23  6.800000
27   03-24  6.000000
31   03-25  6.750000
36   03-26  6.600000
41   03-27  7.000000
46   03-28  6.400000
51   03-29  8.000000
55   03-30  7.500000
60   03-31  7.400000
65   04-01  6.000000
69   04-02  6.500000
74   04-03  6.400000
79   04-04  6.200000
84   04-05  6.800000
88   04-06  6.500000
92   04-07  6.500000
97   04-08  6.600000
102  04-09  7.400000
107  04-10  7.400000
112  04-11  7.000000
116  04-12  7.250000
120  04-13  8.000000
125  04-14  7.200000
130  04-15  6.400000
135  04-16  7.200000
140  04-17  6.600000
145  04-18  6.800000
150  04-19  7.800000
154  04-20  7.250000
159  04-21  7.600000
164  04-22  7.400000
169  04-23  7.600000
174  04-24  7.600000
179  04-25  7.200000
184  04-26  7.600000
188  04-27  7.500000
193  04-28  7.600000
198  04-29  7.000000
203  04-30  7.800000
208  05-01  8.000000
213  05-02  7.600000
218  05-03  8.000000
222  05-04  8.000000