In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics 
from statistics import mean
import copy

In [2]:
#read file
data=pd.read_csv("../Data_mining/data/dataset_mood_smartphone.csv")
data

        Unnamed: 0       id                     time        variable    value
0                1  AS14.01  2014-02-26 13:00:00.000            mood    6.000
1                2  AS14.01  2014-02-26 15:00:00.000            mood    6.000
2                3  AS14.01  2014-02-26 18:00:00.000            mood    6.000
3                4  AS14.01  2014-02-26 21:00:00.000            mood    7.000
4                5  AS14.01  2014-02-27 09:00:00.000            mood    6.000
5                6  AS14.01  2014-02-27 12:00:00.000            mood    6.000
6                7  AS14.01  2014-02-27 15:00:00.000            mood    7.000
7                8  AS14.01  2014-03-21 09:00:00.000            mood    6.000
8                9  AS14.01  2014-03-21 11:00:00.000            mood    6.000
9               10  AS14.01  2014-03-21 15:00:00.000            mood    7.000
10              11  AS14.01  2014-03-21 19:00:00.000            mood    6.000
11              12  AS14.01  2014-03-21 21:00:00.000            mood    6.000
12              13  AS14.01  2014-03-22 08:00:00.000            mood    7.000
13              14  AS14.01  2014-03-22 12:00:00.000            mood    7.000
14              15  AS14.01  2014-03-22 15:00:00.000            mood    7.000
15              16  AS14.01  2014-03-22 18:00:00.000            mood    6.000
16              17  AS14.01  2014-03-22 21:00:00.000            mood    5.000
17              18  AS14.01  2014-03-23 10:00:00.000            mood    7.000
18              19  AS14.01  2014-03-23 12:00:00.000            mood    7.000
19              20  AS14.01  2014-03-23 15:00:00.000            mood    8.000
20              21  AS14.01  2014-03-23 19:00:00.000            mood    6.000
21              22  AS14.01  2014-03-23 21:00:00.000            mood    6.000
22              23  AS14.01  2014-03-24 09:00:00.000            mood    6.000
23              24  AS14.01  2014-03-24 12:00:00.000            mood    6.000
24              25  AS14.01  2014-03-24 15:00:00.000            mood    6.000
25              26  AS14.01  2014-03-24 18:00:00.000            mood    5.000
26              27  AS14.01  2014-03-24 21:00:00.000            mood    7.000
27              28  AS14.01  2014-03-25 09:00:00.000            mood    6.000
28              29  AS14.01  2014-03-25 15:00:00.000            mood    7.000
29              30  AS14.01  2014-03-25 20:00:00.000            mood    8.000
...            ...      ...                      ...             ...      ...
376882     2749463  AS14.28  2014-04-27 10:44:59.062  appCat.weather    1.009
376883     2749481  AS14.28  2014-04-27 10:48:48.413  appCat.weather    9.035
376884     2749546  AS14.28  2014-04-27 12:46:35.697  appCat.weather   24.278
376885     2749602  AS14.28  2014-04-27 13:52:35.108  appCat.weather   15.076
376886     2749608  AS14.28  2014-04-27 13:53:17.608  appCat.weather   39.993
376887     2750181  AS14.28  2014-05-01 20:38:50.595  appCat.weather   40.242
376888     2751060  AS14.28  2014-05-03 21:18:04.157  appCat.weather   43.930
376889     2751227  AS14.28  2014-05-04 08:38:49.355  appCat.weather   12.122
376890     2751229  AS14.28  2014-05-04 08:39:02.530  appCat.weather   17.962
376891     2751518  AS14.28  2014-05-05 06:06:32.828  appCat.weather   11.059
376892     2751730  AS14.28  2014-05-05 20:09:54.138  appCat.weather   42.411
376893     2752088  AS14.28  2014-05-06 20:20:31.098  appCat.weather   31.711
376894     2752310  AS14.28  2014-05-07 13:45:27.233  appCat.weather    1.119
376895     2752401  AS14.28  2014-05-07 16:45:40.653  appCat.weather    8.067
376896     2764945  AS14.30  2014-03-23 08:46:30.237  appCat.weather  344.863
376897     2764968  AS14.30  2014-03-23 12:16:04.568  appCat.weather   22.074
376898     2765154  AS14.30  2014-03-24 08:35:37.507  appCat.weather   15.070
376899     2765807  AS14.30  2014-03-26 08:50:33.236  appCat.weather    6.087
376900     2767251  AS14.30  2014-03-30 13:15:37.865  appCat.weather    1.007
376901     2769195  AS14.30  2014-04-06 10:57:54.450  appCat.weather   51.507
376902     2769196  AS14.30  2014-04-06 11:24:23.055  appCat.weather   41.881
376903     2769197  AS14.30  2014-04-06 11:38:32.033  appCat.weather    4.117
376904     2769509  AS14.30  2014-04-07 18:13:31.111  appCat.weather   11.039
376905     2769513  AS14.30  2014-04-07 18:16:49.107  appCat.weather   60.829
376906     2769514  AS14.30  2014-04-07 18:21:04.197  appCat.weather    3.018
376907     2770399  AS14.30  2014-04-11 07:51:16.948  appCat.weather    8.032
376908     2772465  AS14.30  2014-04-19 11:00:32.747  appCat.weather    3.008
376909     2774026  AS14.30  2014-04-26 10:19:07.434  appCat.weather    7.026
376910     2774133  AS14.30  2014-04-27 00:44:48.450  appCat.weather   23.033
376911     2784435  AS14.32  2014-04-07 18:25:14.036  appCat.weather   22.431

[376912 rows x 5 columns]

### Preprocessing

In [3]:
prev_day="02-26"
new_data=pd.DataFrame(columns=['id', 'time', 'var',"value"])
temp_list=[]
for index, row in data.iterrows():
    
    date=row["time"].split(" ")[0]
    date=date.split("-")[1]+"-"+date.split("-")[2]
    if date != prev_day:
        new_data.loc[index]=[data.loc[index-1]["id"], prev_day , data.loc[index-1]["variable"], statistics.mean(temp_list)]
        temp_list=[row["value"]]
    else:
        temp_list.append(row["value"])
    prev_day=date

In [4]:
new_data

             id   time             var       value
4       AS14.01  02-26            mood    6.250000
7       AS14.01  02-27            mood    6.333333
12      AS14.01  03-21            mood    6.200000
17      AS14.01  03-22            mood    6.400000
22      AS14.01  03-23            mood    6.800000
27      AS14.01  03-24            mood    6.000000
31      AS14.01  03-25            mood    6.750000
36      AS14.01  03-26            mood    6.600000
41      AS14.01  03-27            mood    7.000000
46      AS14.01  03-28            mood    6.400000
51      AS14.01  03-29            mood    8.000000
55      AS14.01  03-30            mood    7.500000
60      AS14.01  03-31            mood    7.400000
65      AS14.01  04-01            mood    6.000000
69      AS14.01  04-02            mood    6.500000
74      AS14.01  04-03            mood    6.400000
79      AS14.01  04-04            mood    6.200000
84      AS14.01  04-05            mood    6.800000
88      AS14.01  04-06            mood    6.500000
92      AS14.01  04-07            mood    6.500000
97      AS14.01  04-08            mood    6.600000
102     AS14.01  04-09            mood    7.400000
107     AS14.01  04-10            mood    7.400000
112     AS14.01  04-11            mood    7.000000
116     AS14.01  04-12            mood    7.250000
120     AS14.01  04-13            mood    8.000000
125     AS14.01  04-14            mood    7.200000
130     AS14.01  04-15            mood    6.400000
135     AS14.01  04-16            mood    7.200000
140     AS14.01  04-17            mood    6.600000
...         ...    ...             ...         ...
376848  AS14.28  04-12  appCat.weather   14.090333
376850  AS14.28  04-13  appCat.weather   53.429500
376852  AS14.28  04-14  appCat.weather   33.129000
376853  AS14.28  04-15  appCat.weather   43.824000
376855  AS14.28  04-16  appCat.weather   39.618000
376857  AS14.28  04-18  appCat.weather   35.589000
376859  AS14.28  04-19  appCat.weather   11.094000
376860  AS14.28  04-21  appCat.weather   39.010000
376863  AS14.28  04-22  appCat.weather   14.918667
376865  AS14.28  04-23  appCat.weather   26.720000
376869  AS14.28  04-24  appCat.weather   32.641250
376873  AS14.28  04-25  appCat.weather   15.677500
376878  AS14.28  04-26  appCat.weather   20.911400
376887  AS14.28  04-27  appCat.weather   18.930222
376888  AS14.28  05-01  appCat.weather   40.242000
376889  AS14.28  05-03  appCat.weather   43.930000
376891  AS14.28  05-04  appCat.weather   15.042000
376893  AS14.28  05-05  appCat.weather   26.735000
376894  AS14.28  05-06  appCat.weather   31.711000
376896  AS14.28  05-07  appCat.weather    4.593000
376898  AS14.30  03-23  appCat.weather  183.468500
376899  AS14.30  03-24  appCat.weather   15.070000
376900  AS14.30  03-26  appCat.weather    6.087000
376901  AS14.30  03-30  appCat.weather    1.007000
376904  AS14.30  04-06  appCat.weather   32.501667
376907  AS14.30  04-07  appCat.weather   24.962000
376908  AS14.30  04-11  appCat.weather    8.032000
376909  AS14.30  04-19  appCat.weather    3.008000
376910  AS14.30  04-26  appCat.weather    7.026000
376911  AS14.30  04-27  appCat.weather   23.033000

[15518 rows x 4 columns]

In [5]:
temps = pd.DataFrame(new_data.values)
dataframe = pd.concat([temps.shift(3), temps.shift(2), temps.shift(1), temps], axis=1)
dataframe.columns = ["id1","time1", "var1","val1","id2","time2", "var2","val2","id3","time3", "var3","val3","id4","time4", "var4","val4"]
dataframe.loc[3:].head()

,id1,time1,var1,val1,id2,time2,var2,val2,id3,time3,var3,val3,id4,time4,var4,val4
3,AS14.01,02-26,mood,6.25,AS14.01,02-27,mood,6.33333,AS14.01,03-21,mood,6.2,AS14.01,03-22,mood,6.4
4,AS14.01,02-27,mood,6.33333,AS14.01,03-21,mood,6.2,AS14.01,03-22,mood,6.4,AS14.01,03-23,mood,6.8
5,AS14.01,03-21,mood,6.2,AS14.01,03-22,mood,6.4,AS14.01,03-23,mood,6.8,AS14.01,03-24,mood,6
6,AS14.01,03-22,mood,6.4,AS14.01,03-23,mood,6.8,AS14.01,03-24,mood,6,AS14.01,03-25,mood,6.75
7,AS14.01,03-23,mood,6.8,AS14.01,03-24,mood,6,AS14.01,03-25,mood,6.75,AS14.01,03-26,mood,6.6

In [6]:
data=dataframe.loc[3:]
df= dataframe.loc[3:]
df['check_var'] = np.where((df['var1'] == df['var2']) & (df['var1'] == df['var3']) & (df['var1'] == df['var4'])
                     , 1 , 0)
df['check_id'] = np.where((df['id1'] == df['id2']) & (df['id1'] == df['id3']) & (df['id1'] == df['id4'])
                     , 1 , 0)
#df['check_date']= np.where((df["time1"].split("-")[0] == df["time2"].split("-")[0]) & 
#                           (df["time1"].split("-")[0] == df["time3"].split("-")[0]) &
#                           (df["time1"].split("-")[0] == df["time4"].split("-")[0]), 1, 0)
df

C:\Users\david\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\david\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,id1,time1,var1,val1,id2,time2,var2,val2,id3,time3,var3,val3,id4,time4,var4,val4,check_var,check_id
3,AS14.01,02-26,mood,6.25,AS14.01,02-27,mood,6.33333,AS14.01,03-21,mood,6.2,AS14.01,03-22,mood,6.4,1,1
4,AS14.01,02-27,mood,6.33333,AS14.01,03-21,mood,6.2,AS14.01,03-22,mood,6.4,AS14.01,03-23,mood,6.8,1,1
5,AS14.01,03-21,mood,6.2,AS14.01,03-22,mood,6.4,AS14.01,03-23,mood,6.8,AS14.01,03-24,mood,6,1,1
6,AS14.01,03-22,mood,6.4,AS14.01,03-23,mood,6.8,AS14.01,03-24,mood,6,AS14.01,03-25,mood,6.75,1,1
7,AS14.01,03-23,mood,6.8,AS14.01,03-24,mood,6,AS14.01,03-25,mood,6.75,AS14.01,03-26,mood,6.6,1,1
8,AS14.01,03-24,mood,6,AS14.01,03-25,mood,6.75,AS14.01,03-26,mood,6.6,AS14.01,03-27,mood,7,1,1
9,AS14.01,03-25,mood,6.75,AS14.01,03-26,mood,6.6,AS14.01,03-27,mood,7,AS14.01,03-28,mood,6.4,1,1
10,AS14.01,03-26,mood,6.6,AS14.01,03-27,mood,7,AS14.01,03-28,mood,6.4,AS14.01,03-29,mood,8,1,1
11,AS14.01,03-27,mood,7,AS14.01,03-28,mood,6.4,AS14.01,03-29,mood,8,AS14.01,03-30,mood,7.5,1,1
12,AS14.01,03-28,mood,6.4,AS14.01,03-29,mood,8,AS14.01,03-30,mood,7.5,AS14.01,03-31,mood,7.4,1,1
13,AS14.01,03-29,mood,8,AS14.01,03-30,mood,7.5,AS14.01,03-31,mood,7.4,AS14.01,04-01,mood,6,1,1
14,AS14.01,03-30,mood,7.5,AS14.01,03-31,mood,7.4,AS14.01,04-01,mood,6,AS14.01,04-02,mood,6.5,1,1
15,AS14.01,03-31,mood,7.4,AS14.01,04-01,mood,6,AS14.01,04-02,mood,6.5,AS14.01,04-03,mood,6.4,1,1
16,AS14.01,04-01,mood,6,AS14.01,04-02,mood,6.5,AS14.01,04-03,mood,6.4,AS14.01,04-04,mood,6.2,1,1
17,AS14.01,04-02,mood,6.5,AS14.01,04-03,mood,6.4,AS14.01,04-04,mood,6.2,AS14.01,04-05,mood,6.8,1,1
18,AS14.01,04-03,mood,6.4,AS14.01,04-04,mood,6.2,AS14.01,04-05,mood,6.8,AS14.01,04-06,mood,6.5,1,1
19,AS14.01,04-04,mood,6.2,AS14.01,04-05,mood,6.8,AS14.01,04-06,mood,6.5,AS14.01,04-07,mood,6.5,1,1
20,AS14.01,04-05,mood,6.8,AS14.01,04-06,mood,6.5,AS14.01,04-07,mood,6.5,AS14.01,04-08,mood,6.6,1,1
21,AS14.01,04-06,mood,6.5,AS14.01,04-07,mood,6.5,AS14.01,04-08,mood,6.6,AS14.01,04-09,mood,7.4,1,1
22,AS14.01,04-07,mood,6.5,AS14.01,04-08,mood,6.6,AS14.01,04-09,mood,7.4,AS14.01,04-10,mood,7.4,1,1
23,AS14.01,04-08,mood,6.6,AS14.01,04-09,mood,7.4,AS14.01,04-10,mood,7.4,AS14.01,04-11,mood,7,1,1
24,AS14.01,04-09,mood,7.4,AS14.01,04-10,mood,7.4,AS14.01,04-11,mood,7,AS14.01,04-12,mood,7.25,1,1
25,AS14.01,04-10,mood,7.4,AS14.01,04-11,mood,7,AS14.01,04-12,mood,7.25,AS14.01,04-13,mood,8,1,1
26,AS14.01,04-11,mood,7,AS14.01,04-12,mood,7.25,AS14.01,04-13,mood,8,AS14.01,04-14,mood,7.2,1,1
27,AS14.01,04-12,mood,7.25,AS14.01,04-13,mood,8,AS14.01,04-14,mood,7.2,AS14.01,04-15,mood,6.4,1,1
28,AS14.01,04-13,mood,8,AS14.01,04-14,mood,7.2,AS14.01,04-15,mood,6.4,AS14.01,04-16,mood,7.2,1,1
29,AS14.01,04-14,mood,7.2,AS14.01,04-15,mood,6.4,AS14.01,04-16,mood,7.2,AS14.01,04-17,mood,6.6,1,1
30,AS14.01,04-15,mood,6.4,AS14.01,04-16,mood,7.2,AS14.01,04-17,mood,6.6,AS14.01,04-18,mood,6.8,1,1
31,AS14.01,04-16,mood,7.2,AS14.01,04-17,mood,6.6,AS14.01,04-18,mood,6.8,AS14.01,04-19,mood,7.8,1,1
32,AS14.01,04-17,mood,6.6,AS14.01,04-18,mood,6.8,AS14.01,04-19,mood,7.8,AS14.01,04-20,mood,7.25,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15488,AS14.28,04-07,appCat.weather,50.0705,AS14.28,04-08,appCat.weather,13.5137,AS14.28,04-11,appCat.weather,10.104,AS14.28,04-12,appCat.weather,14.0903,1,1
15489,AS14.28,04-08,appCat.weather,13.5137,AS14.28,04-11,appCat.weather,10.104,AS14.28,04-12,appCat.weather,14.0903,AS14.28,04-13,appCat.weather,53.4295,1,1
15490,AS14.28,04-11,appCat.weather,10.104,AS14.28,04-12,appCat.weather,14.0903,AS14.28,04-13,appCat.weather,53.4295,AS14.28,04-14,appCat.weather,33.129,1,1
15491,AS14.28,04-12,appCat.weather,14.0903,AS14.28,04-13,appCat.weather,53.4295,AS14.28,04-14,appCat.weather,33.129,AS14.28,04-15,appCat.weather,43.824,1,1
15492,AS14.28,04-13,appCat.weather,53.4295,AS14.28,04-14,appCat.weather,33.129,AS14.28,04-15,appCat.weather,43.824,AS14.28,04-16,appCat.weather,39.618,1,1
15493,AS14.28,04-14,appCat.weather,33.129,AS14.28,04-15,appCat.weather,43.824,AS14.28,04-16,appCat.weather,39.618,AS14.28,04-18,appCat.weather,35.589,1,1
15494,AS14.28,04-15,appCat.weather,43.824,AS14.28,04-16,appCat.weather,39.618,AS14.28,04-18,appCat.weather,35.589,AS14.28,04-19,appCat.weather,11.094,1,1
15495,AS14.28,04-16,appCat.weather,39.618,AS14.28,04-18,appCat.weather,35.589,AS14.28,04-19,appCat.weather,11.094,AS14.28,04-21,appCat.weather,39.01,1,1
15496,AS14.28,04-18,appCat.weather,35.589,AS14.28,04-19,appCat.weather,11.094,AS14.28,04-21,appCat.weather,39.01,AS14.28,04-22,appCat.weather,14.9187,1,1
15497,AS14.28,04-19,appCat.weather,11.094,AS14.28,04-21,appCat.weather,39.01,AS14.28,04-22,appCat.weather,14.9187,AS14.28,04-23,appCat.weather,26.72,1,1
15498,AS14.28,04-21,appCat.weather,39.01,AS14.28,04-22,appCat.weather,14.9187,AS14.28,04-23,appCat.weather,26.72,AS14.28,04-24,appCat.weather,32.6412,1,1
15499,AS14.28,04-22,appCat.weather,14.9187,AS14.28,04-23,appCat.weather,26.72,AS14.28,04-24,appCat.weather,32.6412,AS14.28,04-25,appCat.weather,15.6775,1,1
15500,AS14.28,04-23,appCat.weather,26.72,AS14.28,04-24,appCat.weather,32.6412,AS14.28,04-25,appCat.weather,15.6775,AS14.28,04-26,appCat.weather,20.9114,1,1
15501,AS14.28,04-24,appCat.weather,32.6412,AS14.28,04-25,appCat.weather,15.6775,AS14.28,04-26,appCat.weather,20.9114,AS14.28,04-27,appCat.weather,18.9302,1,1
15502,AS14.28,04-25,appCat.weather,15.6775,AS14.28,04-26,appCat.weather,20.9114,AS14.28,04-27,appCat.weather,18.9302,AS14.28,05-01,appCat.weather,40.242,1,1
15503,AS14.28,04-26,appCat.weather,20.9114,AS14.28,04-27,appCat.weather,18.9302,AS14.28,05-01,appCat.weather,40.242,AS14.28,05-03,appCat.weather,43.93,1,1
15504,AS14.28,04-27,appCat.weather,18.9302,AS14.28,05-01,appCat.weather,40.242,AS14.28,05-03,appCat.weather,43.93,AS14.28,05-04,appCat.weather,15.042,1,1
15505,AS14.28,05-01,appCat.weather,40.242,AS14.28,05-03,appCat.weather,43.93,AS14.28,05-04,appCat.weather,15.042,AS14.28,05-05,appCat.weather,26.735,1,1
15506,AS14.28,05-03,appCat.weather,43.93,AS14.28,05-04,appCat.weather,15.042,AS14.28,05-05,appCat.weather,26.735,AS14.28,05-06,appCat.weather,31.711,1,1
15507,AS14.28,05-04,appCat.weather,15.042,AS14.28,05-05,appCat.weather,26.735,AS14.28,05-06,appCat.weather,31.711,AS14.28,05-07,appCat.weather,4.593,1,1
15508,AS14.28,05-05,appCat.weather,26.735,AS14.28,05-06,appCat.weather,31.711,AS14.28,05-07,appCat.weather,4.593,AS14.30,03-23,appCat.weather,183.469,1,0
15509,AS14.28,05-06,appCat.weather,31.711,AS14.28,05-07,appCat.weather,4.593,AS14.30,03-23,appCat.weather,183.469,AS14.30,03-24,appCat.weather,15.07,1,0
15510,AS14.28,05-07,appCat.weather,4.593,AS14.30,03-23,appCat.weather,183.469,AS14.30,03-24,appCat.weather,15.07,AS14.30,03-26,appCat.weather,6.087,1,0
15511,AS14.30,03-23,appCat.weather,183.469,AS14.30,03-24,appCat.weather,15.07,AS14.30,03-26,appCat.weather,6.087,AS14.30,03-30,appCat.weather,1.007,1,1
15512,AS14.30,03-24,appCat.weather,15.07,AS14.30,03-26,appCat.weather,6.087,AS14.30,03-30,appCat.weather,1.007,AS14.30,04-06,appCat.weather,32.5017,1,1
15513,AS14.30,03-26,appCat.weather,6.087,AS14.30,03-30,appCat.weather,1.007,AS14.30,04-06,appCat.weather,32.5017,AS14.30,04-07,appCat.weather,24.962,1,1
15514,AS14.30,03-30,appCat.weather,1.007,AS14.30,04-06,appCat.weather,32.5017,AS14.30,04-07,appCat.weather,24.962,AS14.30,04-11,appCat.weather,8.032,1,1
15515,AS14.30,04-06,appCat.weather,32.5017,AS14.30,04-07,appCat.weather,24.962,AS14.30,04-11,appCat.weather,8.032,AS14.30,04-19,appCat.weather,3.008,1,1
15516,AS14.30,04-07,appCat.weather,24.962,AS14.30,04-11,appCat.weather,8.032,AS14.30,04-19,appCat.weather,3.008,AS14.30,04-26,appCat.weather,7.026,1,1
15517,AS14.30,04-11,appCat.weather,8.032,AS14.30,04-19,appCat.weather,3.008,AS14.30,04-26,appCat.weather,7.026,AS14.30,04-27,appCat.weather,23.033,1,1

In [7]:
print(df.shape)
#removing rows with different ID and variable
for i, row in df.iterrows():
    if row["check_id"]==0 or row["check_var"]==0:
        data=data.drop(i)
    
data=data.drop(['var2',"var3","var4","id2","id3","id4"], axis=1) 
print(data.shape)
data.head()

(15515, 18)
(14188, 10)

       id1  time1  var1     val1  time2     val2  time3  val3  time4  val4
3  AS14.01  02-26  mood     6.25  02-27  6.33333  03-21   6.2  03-22   6.4
4  AS14.01  02-27  mood  6.33333  03-21      6.2  03-22   6.4  03-23   6.8
5  AS14.01  03-21  mood      6.2  03-22      6.4  03-23   6.8  03-24     6
6  AS14.01  03-22  mood      6.4  03-23      6.8  03-24     6  03-25  6.75
7  AS14.01  03-23  mood      6.8  03-24        6  03-25  6.75  03-26   6.6

In [8]:
data=data[["id1","var1","time1","val1","time2","val2","time3","val3","time4","val4"]].reset_index()
#data.columns = ['a', 'b']
data['time1'] = pd.to_datetime(data['time1'],format="%m-%d")
data['time2'] = pd.to_datetime(data['time2'],format="%m-%d")
data['time3'] = pd.to_datetime(data['time3'],format="%m-%d")
data['time4'] = pd.to_datetime(data['time4'],format="%m-%d")

data.head()

,index,id1,var1,time1,val1,time2,val2,time3,val3,time4,val4
0,3,AS14.01,mood,1900-02-26,6.25,1900-02-27,6.33333,1900-03-21,6.2,1900-03-22,6.4
1,4,AS14.01,mood,1900-02-27,6.33333,1900-03-21,6.2,1900-03-22,6.4,1900-03-23,6.8
2,5,AS14.01,mood,1900-03-21,6.2,1900-03-22,6.4,1900-03-23,6.8,1900-03-24,6
3,6,AS14.01,mood,1900-03-22,6.4,1900-03-23,6.8,1900-03-24,6,1900-03-25,6.75
4,7,AS14.01,mood,1900-03-23,6.8,1900-03-24,6,1900-03-25,6.75,1900-03-26,6.6

In [9]:
data = data.drop(columns=["index"])

In [10]:
data.head()

,id1,var1,time1,val1,time2,val2,time3,val3,time4,val4
0,AS14.01,mood,1900-02-26,6.25,1900-02-27,6.33333,1900-03-21,6.2,1900-03-22,6.4
1,AS14.01,mood,1900-02-27,6.33333,1900-03-21,6.2,1900-03-22,6.4,1900-03-23,6.8
2,AS14.01,mood,1900-03-21,6.2,1900-03-22,6.4,1900-03-23,6.8,1900-03-24,6
3,AS14.01,mood,1900-03-22,6.4,1900-03-23,6.8,1900-03-24,6,1900-03-25,6.75
4,AS14.01,mood,1900-03-23,6.8,1900-03-24,6,1900-03-25,6.75,1900-03-26,6.6

In [11]:
print(data["time1"].iloc[0,])
print(data["time2"].iloc[0,])
delta2=data["time1"].iloc[0,] - data["time2"].iloc[0,]
delta2

1900-02-26 00:00:00
1900-02-27 00:00:00

Timedelta('-1 days +00:00:00')

In [12]:
#check and remove rows with not consecutives days
data_iter=data
for i, row in data_iter.iterrows():
    #print(i)
    delta1=data_iter["time1"].iloc[i,] - data_iter["time2"].iloc[i,]
    delta2=data_iter["time2"].iloc[i,] - data_iter["time3"].iloc[i,]
    delta3=data_iter["time3"].iloc[i,] - data_iter["time4"].iloc[i,]
    delta1=delta1.days
    delta2=delta2.days
    delta3=delta3.days
    if delta1 != -1 or delta2 != -1 or delta3 != -1:
        #print(delta1, delta2, delta3)
        #print("ops")
        data = data.drop(i)

In [14]:
data=data.reset_index()
data = data.drop(columns=["index"])
#data=data.drop(columns="level_0")
data.head()

,id1,var1,time1,val1,time2,val2,time3,val3,time4,val4
0,AS14.01,mood,1900-03-21,6.2,1900-03-22,6.4,1900-03-23,6.8,1900-03-24,6
1,AS14.01,mood,1900-03-22,6.4,1900-03-23,6.8,1900-03-24,6,1900-03-25,6.75
2,AS14.01,mood,1900-03-23,6.8,1900-03-24,6,1900-03-25,6.75,1900-03-26,6.6
3,AS14.01,mood,1900-03-24,6,1900-03-25,6.75,1900-03-26,6.6,1900-03-27,7
4,AS14.01,mood,1900-03-25,6.75,1900-03-26,6.6,1900-03-27,7,1900-03-28,6.4

In [ ]:
# def slope(points):
#     points = np.array(points)
#     x = np.array(range(1,len(points)+1))
#     print(x, points)
#     best_fit = (((mean(x)*mean(points)) - mean(x*points)) /
#                 ((mean(x)^2) - mean(x^2)))
#     return best_fit

In [ ]:
# a=slope([5,4,6,5,6])
# print([1,2,3,4,5],)
a,b = np.polyfit([1,2,3],[6.2,6.4,6.8],1)
new_mood=4*a+b
print(new_mood)

In [15]:
data["val1"] = data["val1"].apply(pd.to_numeric, errors='coerce')
data["val2"] = data["val2"].apply(pd.to_numeric, errors='coerce')
data["val3"] = data["val3"].apply(pd.to_numeric, errors='coerce')
data["val4"] = data["val4"].apply(pd.to_numeric, errors='coerce')
#drop dates
data=data.drop(['time1', 'time2',"time3"], axis=1)
#table = pd.pivot_table(data, values=["val1","val2","val3"], index=['id1', 'time4'], columns=['var1'])
#table["val1","mood"]

#add column with the average 
data['avg'] = data[['val1', 'val2','val3']].mean(axis=1)

In [16]:
slopes=[]
for i, row in data.iterrows():
    a,b = np.polyfit([1,2,3],[row["val1"],row["val2"],row["val3"]],1)
    slopes.append(a)
data["slopes"]=slopes

data

,id1,var1,val1,val2,val3,time4,val4,avg,slopes
0,AS14.01,mood,6.200000,6.400000,6.800000,1900-03-24,6.000000,6.466667,3.000000e-01
1,AS14.01,mood,6.400000,6.800000,6.000000,1900-03-25,6.750000,6.400000,-2.000000e-01
2,AS14.01,mood,6.800000,6.000000,6.750000,1900-03-26,6.600000,6.516667,-2.500000e-02
3,AS14.01,mood,6.000000,6.750000,6.600000,1900-03-27,7.000000,6.450000,3.000000e-01
4,AS14.01,mood,6.750000,6.600000,7.000000,1900-03-28,6.400000,6.783333,1.250000e-01
5,AS14.01,mood,6.600000,7.000000,6.400000,1900-03-29,8.000000,6.666667,-1.000000e-01
6,AS14.01,mood,7.000000,6.400000,8.000000,1900-03-30,7.500000,7.133333,5.000000e-01
7,AS14.01,mood,6.400000,8.000000,7.500000,1900-03-31,7.400000,7.300000,5.500000e-01
8,AS14.01,mood,8.000000,7.500000,7.400000,1900-04-01,6.000000,7.633333,-3.000000e-01
9,AS14.01,mood,7.500000,7.400000,6.000000,1900-04-02,6.500000,6.966667,-7.500000e-01
10,AS14.01,mood,7.400000,6.000000,6.500000,1900-04-03,6.400000,6.633333,-4.500000e-01
11,AS14.01,mood,6.000000,6.500000,6.400000,1900-04-04,6.200000,6.300000,2.000000e-01
12,AS14.01,mood,6.500000,6.400000,6.200000,1900-04-05,6.800000,6.366667,-1.500000e-01
13,AS14.01,mood,6.400000,6.200000,6.800000,1900-04-06,6.500000,6.466667,2.000000e-01
14,AS14.01,mood,6.200000,6.800000,6.500000,1900-04-07,6.500000,6.500000,1.500000e-01
15,AS14.01,mood,6.800000,6.500000,6.500000,1900-04-08,6.600000,6.600000,-1.500000e-01
16,AS14.01,mood,6.500000,6.500000,6.600000,1900-04-09,7.400000,6.533333,5.000000e-02
17,AS14.01,mood,6.500000,6.600000,7.400000,1900-04-10,7.400000,6.833333,4.500000e-01
18,AS14.01,mood,6.600000,7.400000,7.400000,1900-04-11,7.000000,7.133333,4.000000e-01
19,AS14.01,mood,7.400000,7.400000,7.000000,1900-04-12,7.250000,7.266667,-2.000000e-01
20,AS14.01,mood,7.400000,7.000000,7.250000,1900-04-13,8.000000,7.216667,-7.500000e-02
21,AS14.01,mood,7.000000,7.250000,8.000000,1900-04-14,7.200000,7.416667,5.000000e-01
22,AS14.01,mood,7.250000,8.000000,7.200000,1900-04-15,6.400000,7.483333,-2.500000e-02
23,AS14.01,mood,8.000000,7.200000,6.400000,1900-04-16,7.200000,7.200000,-8.000000e-01
24,AS14.01,mood,7.200000,6.400000,7.200000,1900-04-17,6.600000,6.933333,-9.028304e-16
25,AS14.01,mood,6.400000,7.200000,6.600000,1900-04-18,6.800000,6.733333,1.000000e-01
26,AS14.01,mood,7.200000,6.600000,6.800000,1900-04-19,7.800000,6.866667,-2.000000e-01
27,AS14.01,mood,6.600000,6.800000,7.800000,1900-04-20,7.250000,7.066667,6.000000e-01
28,AS14.01,mood,6.800000,7.800000,7.250000,1900-04-21,7.600000,7.283333,2.250000e-01
29,AS14.01,mood,7.800000,7.250000,7.600000,1900-04-22,7.400000,7.550000,-1.000000e-01
...,...,...,...,...,...,...,...,...,...
11091,AS14.31,appCat.utilities,11.461714,44.426500,36.713571,1900-04-29,21.104400,30.867262,1.262593e+01
11092,AS14.31,appCat.utilities,44.426500,36.713571,21.104400,1900-04-30,250.847333,34.081490,-1.166105e+01
11093,AS14.31,appCat.utilities,36.713571,21.104400,250.847333,1900-05-01,146.964500,102.888435,1.070669e+02
11094,AS14.31,appCat.utilities,21.104400,250.847333,146.964500,1900-05-02,38.998091,139.638744,6.293005e+01
11095,AS14.31,appCat.utilities,250.847333,146.964500,38.998091,1900-05-03,231.586000,145.603308,-1.059246e+02
11096,AS14.33,appCat.utilities,13.744333,8.336618,6.824600,1900-04-19,5.995643,9.635184,-3.459867e+00
11097,AS14.33,appCat.utilities,8.336618,6.824600,5.995643,1900-04-20,3.010000,7.052287,-1.170487e+00
11098,AS14.33,appCat.utilities,6.824600,5.995643,3.010000,1900-04-21,4.208000,5.276748,-1.907300e+00
11099,AS14.33,appCat.utilities,5.995643,3.010000,4.208000,1900-04-22,5.301882,4.404548,-8.938214e-01
11100,AS14.33,appCat.utilities,5.674250,2.488000,9.623971,1900-04-29,6.974000,5.928740,1.974861e+00
11101,AS14.33,appCat.utilities,3.865750,3.187000,6.568625,1900-05-09,4.119250,4.540458,1.351437e+00
11102,AS14.33,appCat.utilities,3.187000,6.568625,4.119250,1900-05-10,21.935000,4.624958,4.661250e-01
11103,AS14.33,appCat.utilities,18.724333,5.111000,1.599500,1900-05-30,15.521667,8.478278,-8.562417e+00
11104,AS14.25,appCat.weather,26.830000,7.031000,33.173000,1900-04-16,5.033000,22.344667,3.171500e+00
11105,AS14.25,appCat.weather,9.393667,5.931667,5.067000,1900-05-01,15.079000,6.797444,-2.163333e+00
11106,AS14.25,appCat.weather,41.287000,16.079000,26.117000,1900-05-07,6.024000,27.827667,-7.585000e+00
11107,AS14.25,appCat.weather,16.079000,26.117000,6.024000,1900-05-08,13.111000,16.073333,-5.027500e+00
11108,AS14.26,appCat.weather,3.109500,12.223000,18.629000,1900-04-25,12.975875,11.320500,7.759750e+00
11109,AS14.26,appCat.weather,11.103143,26.515000,9.650750,1900-05-11,5.008250,15.756298,-7.261964e-01
11110,AS14.27,appCat.weather,23.144000,19.499750,20.223800,1900-05-12,31.067000,20.955850,-1.460100e+00
11111,AS14.28,appCat.weather,45.055000,29.228333,28.765000,1900-04-05,5.050000,34.349444,-8.145000e+00
11112,AS14.28,appCat.weather,10.104000,14.090333,53.429500,1900-04-14,33.129000,25.874611,2.166275e+01
11113,AS14.28,appCat.weather,14.090333,53.429500,33.129000,1900-04-15,43.824000,33.549611,9.519333e+00
11114,AS14.28,appCat.weather,53.429500,33.129000,43.824000,1900-04-16,39.618000,43.460833,-4.802750e+00
11115,AS14.28,appCat.weather,39.010000,14.918667,26.720000,1900-04-24,32.641250,26.882889,-6.145000e+00
11116,AS14.28,appCat.weather,14.918667,26.720000,32.641250,1900-04-25,15.677500,24.759972,8.861292e+00
11117,AS14.28,appCat.weather,26.720000,32.641250,15.677500,1900-04-26,20.911400,25.012917,-5.521250e+00
11118,AS14.28,appCat.weather,32.641250,15.677500,20.911400,1900-04-27,18.930222,23.076717,-5.864925e+00
11119,AS14.28,appCat.weather,43.930000,15.042000,26.735000,1900-05-06,31.711000,28.569000,-8.597500e+00
11120,AS14.28,appCat.weather,15.042000,26.735000,31.711000,1900-05-07,4.593000,24.496000,8.334500e+00

In [20]:
data=data.rename(index=str, columns={"val4": "mood_target"})
data=data.drop(['val1', 'val2',"val3"], axis=1)

KeyError: "['val1' 'val2' 'val3'] not found in axis"

In [38]:
data.head()

       id1  var1      time4  mood_target       avg  slopes
0  AS14.01  mood 1900-03-24         6.00  6.466667   0.300
1  AS14.01  mood 1900-03-25         6.75  6.400000  -0.200
2  AS14.01  mood 1900-03-26         6.60  6.516667  -0.025
3  AS14.01  mood 1900-03-27         7.00  6.450000   0.300
4  AS14.01  mood 1900-03-28         6.40  6.783333   0.125

In [39]:
table = pd.pivot_table(data, values=['avg',"slopes","mood_target"], index=['id1', 'time4'], columns=['var1'])
table

                         avg                                      \
var1                activity appCat.builtin appCat.communication
id1     time4
AS14.01 1900-02-20       NaN            NaN                  NaN
        1900-02-22       NaN            NaN                  NaN
        1900-03-13       NaN            NaN                  NaN
        1900-03-14       NaN            NaN                  NaN
        1900-03-17       NaN            NaN                  NaN
        1900-03-18       NaN            NaN                  NaN
        1900-03-21       NaN            NaN                  NaN
        1900-03-22       NaN            NaN                  NaN
        1900-03-23  0.150826       9.326135            55.131124
        1900-03-24  0.171224      11.394910            53.411540
        1900-03-25  0.152861       8.299354            50.893593
        1900-03-26  0.106692       9.047925            56.807075
        1900-03-27  0.092881       7.823168            54.680243
        1900-03-28  0.119731       8.823213            53.284080
        1900-03-29  0.118839      32.530909            38.164476
        1900-03-30  0.107804      37.552755            38.387778
        1900-03-31  0.070998      37.497943            44.547901
        1900-04-01  0.062600      16.121146            50.301094
        1900-04-02  0.079347      10.195603            45.433234
        1900-04-03  0.096955      13.065820            36.074330
        1900-04-04  0.089866      10.451213            37.769806
        1900-04-05  0.092615      11.933877            41.582547
        1900-04-06  0.098310      60.791605            42.899654
        1900-04-07  0.103366      69.048103            43.404482
        1900-04-08  0.078027      68.008832            47.554329
        1900-04-09  0.063468      15.570123            51.353766
        1900-04-10  0.082127       7.449229            48.084070
        1900-04-11  0.091558       7.318011            50.774024
        1900-04-12  0.093111      13.444208            43.596906
        1900-04-13  0.077066      12.116973            78.677330
...                      ...            ...                  ...
AS14.33 1900-05-02  0.090247      13.752903                  NaN
        1900-05-03  0.177196      12.985922                  NaN
        1900-05-04  0.273121      44.874070                  NaN
        1900-05-05  0.328317      45.768136                  NaN
        1900-05-06  0.226589      49.868461            29.183075
        1900-05-07  0.151887      16.616349            57.883738
        1900-05-08  0.038036      13.390913            47.272863
        1900-05-09  0.052171       8.281477            56.550670
        1900-05-10  0.031675       9.497423            44.059335
        1900-05-11  0.062745      11.454699            47.725196
        1900-05-12  0.040528       8.513500            38.708690
        1900-05-13  0.043383      10.352339            41.726266
        1900-05-14  0.058382      12.707622            74.805459
        1900-05-15  0.055989      13.542141            71.730276
        1900-05-16  0.088827      11.918538            63.481423
        1900-05-17  0.059433      11.194918            38.249215
        1900-05-18  0.063662      12.550997            38.834593
        1900-05-19  0.028729      14.814977            52.042891
        1900-05-20  0.014518      10.924600            49.208135
        1900-05-21  0.015087      10.193739            71.814165
        1900-05-22  0.014903       7.431959            66.436490
        1900-05-23  0.015700       8.834740            70.542827
        1900-05-24  0.016435       9.972748            50.831061
        1900-05-25  0.015470      10.583167            41.537724
        1900-05-26  0.065448      12.940546            38.002251
        1900-05-27  0.096986      11.710031            37.024878
        1900-05-28  0.096459      10.751688            42.844427
        1900-05-29  0.077069       8.615830            43.647388
        1900-05-30  0.095120       8.196112            50.336606
        1900-05-31       NaN            NaN                  NaN

                                                                    \
var1               appCat.entertainment appCat.finance appCat.game
id1     time4
AS14.01 1900-02-20                  NaN            NaN         NaN
        1900-02-22                  NaN            NaN         NaN
        1900-03-13                  NaN            NaN         NaN
        1900-03-14                  NaN            NaN         NaN
        1900-03-17                  NaN            NaN         NaN
        1900-03-18                  NaN            NaN         NaN
        1900-03-21                  NaN            NaN         NaN
        1900-03-22                  NaN            NaN         NaN
        1900-03-23            52.720667            NaN         NaN
        1900-03-24            43.711556       8.023028         NaN
        1900-03-25            66.744014       7.853472         NaN
        1900-03-26            62.557681       9.099528         NaN
        1900-03-27            95.430935       8.389889         NaN
        1900-03-28            78.403032      11.186111         NaN
        1900-03-29            97.502123            NaN         NaN
        1900-03-30            90.311069            NaN         NaN
        1900-03-31           123.508772            NaN         NaN
        1900-04-01           110.286329            NaN         NaN
        1900-04-02            88.435642            NaN         NaN
        1900-04-03            46.999820      11.711372         NaN
        1900-04-04            46.340519            NaN         NaN
        1900-04-05            64.218345            NaN         NaN
        1900-04-06            74.233575            NaN         NaN
        1900-04-07            88.850896            NaN         NaN
        1900-04-08            81.498722            NaN         NaN
        1900-04-09           111.065865            NaN         NaN
        1900-04-10           105.996032            NaN         NaN
        1900-04-11           132.791893            NaN         NaN
        1900-04-12           118.937958            NaN         NaN
        1900-04-13           153.541069            NaN         NaN
...                                 ...            ...         ...
AS14.33 1900-05-02                  NaN            NaN         NaN
        1900-05-03                  NaN            NaN         NaN
        1900-05-04                  NaN            NaN         NaN
        1900-05-05                  NaN            NaN         NaN
        1900-05-06            41.349273            NaN         NaN
        1900-05-07            54.867135            NaN         NaN
        1900-05-08            70.891888            NaN         NaN
        1900-05-09            74.081293            NaN         NaN
        1900-05-10            84.616552            NaN         NaN
        1900-05-11            75.731237            NaN         NaN
        1900-05-12            57.019223            NaN         NaN
        1900-05-13            52.080935            NaN         NaN
        1900-05-14            63.944278            NaN         NaN
        1900-05-15            99.577167            NaN         NaN
        1900-05-16            94.310902            NaN         NaN
        1900-05-17            75.818938            NaN         NaN
        1900-05-18            46.646873            NaN         NaN
        1900-05-19            53.217193            NaN         NaN
        1900-05-20            73.143407            NaN         NaN
        1900-05-21           100.503689            NaN         NaN
        1900-05-22           103.117067            NaN         NaN
        1900-05-23            97.510511            NaN         NaN
        1900-05-24           139.604378            NaN         NaN
        1900-05-25           142.807230            NaN         NaN
        1900-05-26           134.334008            NaN         NaN
        1900-05-27            71.443641            NaN         NaN
        1900-05-28            65.320856            NaN         NaN
        1900-05-29            58.377157            NaN         NaN
        1900-05-30            58.207857            NaN         NaN
        1900-05-31                  NaN            NaN         NaN

                                                                           \
var1               appCat.office appCat.other appCat.social appCat.travel
id1     time4
AS14.01 1900-02-20           NaN          NaN           NaN           NaN
        1900-02-22           NaN          NaN           NaN           NaN
        1900-03-13           NaN          NaN           NaN           NaN
        1900-03-14           NaN          NaN           NaN           NaN
        1900-03-17           NaN          NaN           NaN           NaN
        1900-03-18           NaN          NaN           NaN           NaN
        1900-03-21           NaN          NaN           NaN           NaN
        1900-03-22           NaN          NaN           NaN           NaN
        1900-03-23           NaN    16.553935     61.735919           NaN
        1900-03-24           NaN    18.708823     53.941426           NaN
        1900-03-25           NaN    12.416865     53.883553           NaN
        1900-03-26           NaN    17.677778     64.522398           NaN
        1900-03-27           NaN    19.048611     89.210095           NaN
        1900-03-28           NaN    18.602722     88.204874           NaN
        1900-03-29           NaN    21.221167     73.899712           NaN
        1900-03-30           NaN    23.880516     52.233478           NaN
        1900-03-31           NaN    24.740016     46.881017           NaN
        1900-04-01           NaN    20.325183     57.094431           NaN
        1900-04-02           NaN    17.298861     52.663694           NaN
        1900-04-03           NaN    21.036004     55.596757           NaN
        1900-04-04           NaN    17.651381     51.646303           NaN
        1900-04-05           NaN    19.968506     60.352649           NaN
        1900-04-06           NaN    15.983562     53.921586           NaN
        1900-04-07           NaN    17.847962     60.543609           NaN
        1900-04-08           NaN    17.579087     57.056250           NaN
        1900-04-09           NaN    23.692468     61.590146           NaN
        1900-04-10           NaN    31.518607     54.880053           NaN
        1900-04-11           NaN    28.917399     47.440547           NaN
        1900-04-12           NaN    21.798986     43.075728           NaN
        1900-04-13           NaN    11.118546     43.045821           NaN
...                          ...          ...           ...           ...
AS14.33 1900-05-02           NaN    12.996933           NaN           NaN
        1900-05-03           NaN    12.494124           NaN           NaN
        1900-05-04           NaN    11.927524           NaN           NaN
        1900-05-05           NaN    11.703933           NaN           NaN
        1900-05-06           NaN          NaN     73.894927           NaN
        1900-05-07           NaN          NaN     90.867870     48.976967
        1900-05-08           NaN          NaN    110.590068     41.033500
        1900-05-09           NaN          NaN    124.206648     36.111056
        1900-05-10           NaN    13.683972    149.698463     20.709889
        1900-05-11           NaN    14.795422    120.741117     33.152889
        1900-05-12           NaN    12.099600    104.362074           NaN
        1900-05-13           NaN    24.429989     83.946048           NaN
        1900-05-14           NaN    24.255011     91.989457           NaN
        1900-05-15           NaN    25.492611    129.165560           NaN
        1900-05-16           NaN    13.593722    124.968558           NaN
        1900-05-17           NaN    13.459556    123.860299           NaN
        1900-05-18           NaN    11.937472     79.226402           NaN
        1900-05-19           NaN    11.721172     90.915993           NaN
        1900-05-20           NaN    12.472617    110.201611           NaN
        1900-05-21           NaN    12.973867    132.929168           NaN
        1900-05-22           NaN    12.571722    134.010736           NaN
        1900-05-23           NaN    13.253889    109.742962           NaN
        1900-05-24           NaN    14.510532    123.089888           NaN
        1900-05-25           NaN    15.094421    118.335189           NaN
        1900-05-26           NaN    12.930921    116.105361           NaN
        1900-05-27           NaN    13.502611     88.057196           NaN
        1900-05-28           NaN    15.090583     68.946588           NaN
        1900-05-29           NaN    20.857715     86.862330           NaN
        1900-05-30           NaN    18.487215    116.140336           NaN
        1900-05-31           NaN          NaN           NaN           NaN

                        ...             slopes                 \
var1                    ...      appCat.travel appCat.unknown
id1     time4           ...
AS14.01 1900-02-20      ...                NaN            NaN
        1900-02-22      ...                NaN            NaN
        1900-03-13      ...                NaN            NaN
        1900-03-14      ...                NaN            NaN
        1900-03-17      ...                NaN            NaN
        1900-03-18      ...                NaN            NaN
        1900-03-21      ...                NaN            NaN
        1900-03-22      ...                NaN            NaN
        1900-03-23      ...                NaN            NaN
        1900-03-24      ...                NaN            NaN
        1900-03-25      ...                NaN            NaN
        1900-03-26      ...                NaN            NaN
        1900-03-27      ...                NaN            NaN
        1900-03-28      ...                NaN            NaN
        1900-03-29      ...                NaN            NaN
        1900-03-30      ...                NaN            NaN
        1900-03-31      ...                NaN            NaN
        1900-04-01      ...                NaN            NaN
        1900-04-02      ...                NaN            NaN
        1900-04-03      ...                NaN            NaN
        1900-04-04      ...                NaN            NaN
        1900-04-05      ...                NaN            NaN
        1900-04-06      ...                NaN            NaN
        1900-04-07      ...                NaN            NaN
        1900-04-08      ...                NaN            NaN
        1900-04-09      ...                NaN            NaN
        1900-04-10      ...                NaN            NaN
        1900-04-11      ...                NaN            NaN
        1900-04-12      ...                NaN            NaN
        1900-04-13      ...                NaN            NaN
...                     ...                ...            ...
AS14.33 1900-05-02      ...                NaN            NaN
        1900-05-03      ...                NaN            NaN
        1900-05-04      ...                NaN            NaN
        1900-05-05      ...                NaN            NaN
        1900-05-06      ...                NaN            NaN
        1900-05-07      ...          10.145050            NaN
        1900-05-08      ...         -36.245500            NaN
        1900-05-09      ...           6.801583            NaN
        1900-05-10      ...          -1.041500            NaN
        1900-05-11      ...         -10.197333            NaN
        1900-05-12      ...                NaN            NaN
        1900-05-13      ...                NaN            NaN
        1900-05-14      ...                NaN            NaN
        1900-05-15      ...                NaN            NaN
        1900-05-16      ...                NaN            NaN
        1900-05-17      ...                NaN            NaN
        1900-05-18      ...                NaN            NaN
        1900-05-19      ...                NaN            NaN
        1900-05-20      ...                NaN            NaN
        1900-05-21      ...                NaN            NaN
        1900-05-22      ...                NaN            NaN
        1900-05-23      ...                NaN            NaN
        1900-05-24      ...                NaN            NaN
        1900-05-25      ...                NaN            NaN
        1900-05-26      ...                NaN            NaN
        1900-05-27      ...                NaN            NaN
        1900-05-28      ...                NaN            NaN
        1900-05-29      ...                NaN            NaN
        1900-05-30      ...                NaN            NaN
        1900-05-31      ...                NaN            NaN

                                                                  \
var1               appCat.utilities appCat.weather          call
id1     time4
AS14.01 1900-02-20              NaN            NaN -8.185332e-17
        1900-02-22              NaN            NaN           NaN
        1900-03-13              NaN            NaN -8.185332e-17
        1900-03-14              NaN            NaN -8.185332e-17
        1900-03-17              NaN            NaN           NaN
        1900-03-18              NaN            NaN           NaN
        1900-03-21              NaN            NaN -8.185332e-17
        1900-03-22              NaN            NaN -8.185332e-17
        1900-03-23        14.335000            NaN           NaN
        1900-03-24         3.528500            NaN           NaN
        1900-03-25        25.079500            NaN           NaN
        1900-03-26        -3.898350            NaN           NaN
        1900-03-27       -28.000500            NaN           NaN
        1900-03-28        -3.006968            NaN           NaN
        1900-03-29        -1.596650            NaN           NaN
        1900-03-30         4.375589            NaN           NaN
        1900-03-31         4.062150            NaN           NaN
        1900-04-01        -6.327830            NaN           NaN
        1900-04-02        -9.562148            NaN           NaN
        1900-04-03         4.482403            NaN -8.185332e-17
        1900-04-04        -2.556160            NaN -8.185332e-17
        1900-04-05        -5.718151            NaN           NaN
        1900-04-06        -0.421026            NaN           NaN
        1900-04-07        -0.324792            NaN           NaN
        1900-04-08        19.117708            NaN           NaN
        1900-04-09         4.410850            NaN -8.185332e-17
        1900-04-10        32.009525            NaN -8.185332e-17
        1900-04-11         3.553817            NaN           NaN
        1900-04-12       -45.811011            NaN           NaN
        1900-04-13              NaN            NaN           NaN
...                             ...            ...           ...
AS14.33 1900-05-02              NaN            NaN -8.185332e-17
        1900-05-03              NaN            NaN -8.185332e-17
        1900-05-04              NaN            NaN -8.185332e-17
        1900-05-05              NaN            NaN -8.185332e-17
        1900-05-06              NaN            NaN -8.185332e-17
        1900-05-07              NaN            NaN -8.185332e-17
        1900-05-08              NaN            NaN -8.185332e-17
        1900-05-09         1.351437            NaN           NaN
        1900-05-10         0.466125            NaN           NaN
        1900-05-11              NaN            NaN           NaN
        1900-05-12              NaN            NaN           NaN
        1900-05-13              NaN            NaN           NaN
        1900-05-14              NaN            NaN           NaN

In [63]:
table_test=table
list_to_remove=[("mood_target","activity"),("mood_target","appCat.builtin"),("mood_target","appCat.communication"),("mood_target","appCat.entertainment"),
               ("mood_target","appCat.finance"),("mood_target","appCat.game"),("mood_target","appCat.office"),
               ("mood_target","appCat.other"),("mood_target","appCat.social"),("mood_target","appCat.travel"),
               ("mood_target","appCat.unknown"),("mood_target","appCat.utilities"),("mood_target","appCat.weather"),
               ("mood_target","call"),("mood_target","circumplex.arousal"),("mood_target","circumplex.valence"),
               ("mood_target","screen"),("mood_target","sms")]
table_test=table_test.drop(list_to_remove, axis =1)
#table_test.iloc[:]["mood_target"]
table_test

                         avg                                      \
var1                activity appCat.builtin appCat.communication
id1     time4
AS14.01 1900-02-20       NaN            NaN                  NaN
        1900-02-22       NaN            NaN                  NaN
        1900-03-13       NaN            NaN                  NaN
        1900-03-14       NaN            NaN                  NaN
        1900-03-17       NaN            NaN                  NaN
        1900-03-18       NaN            NaN                  NaN
        1900-03-21       NaN            NaN                  NaN
        1900-03-22       NaN            NaN                  NaN
        1900-03-23  0.150826       9.326135            55.131124
        1900-03-24  0.171224      11.394910            53.411540
        1900-03-25  0.152861       8.299354            50.893593
        1900-03-26  0.106692       9.047925            56.807075
        1900-03-27  0.092881       7.823168            54.680243
        1900-03-28  0.119731       8.823213            53.284080
        1900-03-29  0.118839      32.530909            38.164476
        1900-03-30  0.107804      37.552755            38.387778
        1900-03-31  0.070998      37.497943            44.547901
        1900-04-01  0.062600      16.121146            50.301094
        1900-04-02  0.079347      10.195603            45.433234
        1900-04-03  0.096955      13.065820            36.074330
        1900-04-04  0.089866      10.451213            37.769806
        1900-04-05  0.092615      11.933877            41.582547
        1900-04-06  0.098310      60.791605            42.899654
        1900-04-07  0.103366      69.048103            43.404482
        1900-04-08  0.078027      68.008832            47.554329
        1900-04-09  0.063468      15.570123            51.353766
        1900-04-10  0.082127       7.449229            48.084070
        1900-04-11  0.091558       7.318011            50.774024
        1900-04-12  0.093111      13.444208            43.596906
        1900-04-13  0.077066      12.116973            78.677330
...                      ...            ...                  ...
AS14.33 1900-05-02  0.090247      13.752903                  NaN
        1900-05-03  0.177196      12.985922                  NaN
        1900-05-04  0.273121      44.874070                  NaN
        1900-05-05  0.328317      45.768136                  NaN
        1900-05-06  0.226589      49.868461            29.183075
        1900-05-07  0.151887      16.616349            57.883738
        1900-05-08  0.038036      13.390913            47.272863
        1900-05-09  0.052171       8.281477            56.550670
        1900-05-10  0.031675       9.497423            44.059335
        1900-05-11  0.062745      11.454699            47.725196
        1900-05-12  0.040528       8.513500            38.708690
        1900-05-13  0.043383      10.352339            41.726266
        1900-05-14  0.058382      12.707622            74.805459
        1900-05-15  0.055989      13.542141            71.730276
        1900-05-16  0.088827      11.918538            63.481423
        1900-05-17  0.059433      11.194918            38.249215
        1900-05-18  0.063662      12.550997            38.834593
        1900-05-19  0.028729      14.814977            52.042891
        1900-05-20  0.014518      10.924600            49.208135
        1900-05-21  0.015087      10.193739            71.814165
        1900-05-22  0.014903       7.431959            66.436490
        1900-05-23  0.015700       8.834740            70.542827
        1900-05-24  0.016435       9.972748            50.831061
        1900-05-25  0.015470      10.583167            41.537724
        1900-05-26  0.065448      12.940546            38.002251
        1900-05-27  0.096986      11.710031            37.024878
        1900-05-28  0.096459      10.751688            42.844427
        1900-05-29  0.077069       8.615830            43.647388
        1900-05-30  0.095120       8.196112            50.336606
        1900-05-31       NaN            NaN                  NaN

                                                                    \
var1               appCat.entertainment appCat.finance appCat.game
id1     time4
AS14.01 1900-02-20                  NaN            NaN         NaN
        1900-02-22                  NaN            NaN         NaN
        1900-03-13                  NaN            NaN         NaN
        1900-03-14                  NaN            NaN         NaN
        1900-03-17                  NaN            NaN         NaN
        1900-03-18                  NaN            NaN         NaN
        1900-03-21                  NaN            NaN         NaN
        1900-03-22                  NaN            NaN         NaN
        1900-03-23            52.720667            NaN         NaN
        1900-03-24            43.711556       8.023028         NaN
        1900-03-25            66.744014       7.853472         NaN
        1900-03-26            62.557681       9.099528         NaN
        1900-03-27            95.430935       8.389889         NaN
        1900-03-28            78.403032      11.186111         NaN
        1900-03-29            97.502123            NaN         NaN
        1900-03-30            90.311069            NaN         NaN
        1900-03-31           123.508772            NaN         NaN
        1900-04-01           110.286329            NaN         NaN
        1900-04-02            88.435642            NaN         NaN
        1900-04-03            46.999820      11.711372         NaN
        1900-04-04            46.340519            NaN         NaN
        1900-04-05            64.218345            NaN         NaN
        1900-04-06            74.233575            NaN         NaN
        1900-04-07            88.850896            NaN         NaN
        1900-04-08            81.498722            NaN         NaN
        1900-04-09           111.065865            NaN         NaN
        1900-04-10           105.996032            NaN         NaN
        1900-04-11           132.791893            NaN         NaN
        1900-04-12           118.937958            NaN         NaN
        1900-04-13           153.541069            NaN         NaN
...                                 ...            ...         ...
AS14.33 1900-05-02                  NaN            NaN         NaN
        1900-05-03                  NaN            NaN         NaN
        1900-05-04                  NaN            NaN         NaN
        1900-05-05                  NaN            NaN         NaN
        1900-05-06            41.349273            NaN         NaN
        1900-05-07            54.867135            NaN         NaN
        1900-05-08            70.891888            NaN         NaN
        1900-05-09            74.081293            NaN         NaN
        1900-05-10            84.616552            NaN         NaN
        1900-05-11            75.731237            NaN         NaN
        1900-05-12            57.019223            NaN         NaN
        1900-05-13            52.080935            NaN         NaN
        1900-05-14            63.944278            NaN         NaN
        1900-05-15            99.577167            NaN         NaN
        1900-05-16            94.310902            NaN         NaN
        1900-05-17            75.818938            NaN         NaN
        1900-05-18            46.646873            NaN         NaN
        1900-05-19            53.217193            NaN         NaN
        1900-05-20            73.143407            NaN         NaN
        1900-05-21           100.503689            NaN         NaN
        1900-05-22           103.117067            NaN         NaN
        1900-05-23            97.510511            NaN         NaN
        1900-05-24           139.604378            NaN         NaN
        1900-05-25           142.807230            NaN         NaN
        1900-05-26           134.334008            NaN         NaN
        1900-05-27            71.443641            NaN         NaN
        1900-05-28            65.320856            NaN         NaN
        1900-05-29            58.377157            NaN         NaN
        1900-05-30            58.207857            NaN         NaN
        1900-05-31                  NaN            NaN         NaN

                                                                           \
var1               appCat.office appCat.other appCat.social appCat.travel
id1     time4
AS14.01 1900-02-20           NaN          NaN           NaN           NaN
        1900-02-22           NaN          NaN           NaN           NaN
        1900-03-13           NaN          NaN           NaN           NaN
        1900-03-14           NaN          NaN           NaN           NaN
        1900-03-17           NaN          NaN           NaN           NaN
        1900-03-18           NaN          NaN           NaN           NaN
        1900-03-21           NaN          NaN           NaN           NaN
        1900-03-22           NaN          NaN           NaN           NaN
        1900-03-23           NaN    16.553935     61.735919           NaN
        1900-03-24           NaN    18.708823     53.941426           NaN
        1900-03-25           NaN    12.416865     53.883553           NaN
        1900-03-26           NaN    17.677778     64.522398           NaN
        1900-03-27           NaN    19.048611     89.210095           NaN
        1900-03-28           NaN    18.602722     88.204874           NaN
        1900-03-29           NaN    21.221167     73.899712           NaN
        1900-03-30           NaN    23.880516     52.233478           NaN
        1900-03-31           NaN    24.740016     46.881017           NaN
        1900-04-01           NaN    20.325183     57.094431           NaN
        1900-04-02           NaN    17.298861     52.663694           NaN
        1900-04-03           NaN    21.036004     55.596757           NaN
        1900-04-04           NaN    17.651381     51.646303           NaN
        1900-04-05           NaN    19.968506     60.352649           NaN
        1900-04-06           NaN    15.983562     53.921586           NaN
        1900-04-07           NaN    17.847962     60.543609           NaN
        1900-04-08           NaN    17.579087     57.056250           NaN
        1900-04-09           NaN    23.692468     61.590146           NaN
        1900-04-10           NaN    31.518607     54.880053           NaN
        1900-04-11           NaN    28.917399     47.440547           NaN
        1900-04-12           NaN    21.798986     43.075728           NaN
        1900-04-13           NaN    11.118546     43.045821           NaN
...                          ...          ...           ...           ...
AS14.33 1900-05-02           NaN    12.996933           NaN           NaN
        1900-05-03           NaN    12.494124           NaN           NaN
        1900-05-04           NaN    11.927524           NaN           NaN
        1900-05-05           NaN    11.703933           NaN           NaN
        1900-05-06           NaN          NaN     73.894927           NaN
        1900-05-07           NaN          NaN     90.867870     48.976967
        1900-05-08           NaN          NaN    110.590068     41.033500
        1900-05-09           NaN          NaN    124.206648     36.111056
        1900-05-10           NaN    13.683972    149.698463     20.709889
        1900-05-11           NaN    14.795422    120.741117     33.152889
        1900-05-12           NaN    12.099600    104.362074           NaN
        1900-05-13           NaN    24.429989     83.946048           NaN
        1900-05-14           NaN    24.255011     91.989457           NaN
        1900-05-15           NaN    25.492611    129.165560           NaN
        1900-05-16           NaN    13.593722    124.968558           NaN
        1900-05-17           NaN    13.459556    123.860299           NaN
        1900-05-18           NaN    11.937472     79.226402           NaN
        1900-05-19           NaN    11.721172     90.915993           NaN
        1900-05-20           NaN    12.472617    110.201611           NaN
        1900-05-21           NaN    12.973867    132.929168           NaN
        1900-05-22           NaN    12.571722    134.010736           NaN
        1900-05-23           NaN    13.253889    109.742962           NaN
        1900-05-24           NaN    14.510532    123.089888           NaN
        1900-05-25           NaN    15.094421    118.335189           NaN
        1900-05-26           NaN    12.930921    116.105361           NaN
        1900-05-27           NaN    13.502611     88.057196           NaN
        1900-05-28           NaN    15.090583     68.946588           NaN
        1900-05-29           NaN    20.857715     86.862330           NaN
        1900-05-30           NaN    18.487215    116.140336           NaN
        1900-05-31           NaN          NaN           NaN           NaN

                        ...             slopes                 \
var1                    ...      appCat.travel appCat.unknown
id1     time4           ...
AS14.01 1900-02-20      ...                NaN            NaN
        1900-02-22      ...                NaN            NaN
        1900-03-13      ...                NaN            NaN
        1900-03-14      ...                NaN            NaN
        1900-03-17      ...                NaN            NaN
        1900-03-18      ...                NaN            NaN
        1900-03-21      ...                NaN            NaN
        1900-03-22      ...                NaN            NaN
        1900-03-23      ...                NaN            NaN
        1900-03-24      ...                NaN            NaN
        1900-03-25      ...                NaN            NaN
        1900-03-26      ...                NaN            NaN
        1900-03-27      ...                NaN            NaN
        1900-03-28      ...                NaN            NaN
        1900-03-29      ...                NaN            NaN
        1900-03-30      ...                NaN            NaN
        1900-03-31      ...                NaN            NaN
        1900-04-01      ...                NaN            NaN
        1900-04-02      ...                NaN            NaN
        1900-04-03      ...                NaN            NaN
        1900-04-04      ...                NaN            NaN
        1900-04-05      ...                NaN            NaN
        1900-04-06      ...                NaN            NaN
        1900-04-07      ...                NaN            NaN
        1900-04-08      ...                NaN            NaN
        1900-04-09      ...                NaN            NaN
        1900-04-10      ...                NaN            NaN
        1900-04-11      ...                NaN            NaN
        1900-04-12      ...                NaN            NaN
        1900-04-13      ...                NaN            NaN
...                     ...                ...            ...
AS14.33 1900-05-02      ...                NaN            NaN
        1900-05-03      ...                NaN            NaN
        1900-05-04      ...                NaN            NaN
        1900-05-05      ...                NaN            NaN
        1900-05-06      ...                NaN            NaN
        1900-05-07      ...          10.145050            NaN
        1900-05-08      ...         -36.245500            NaN
        1900-05-09      ...           6.801583            NaN
        1900-05-10      ...          -1.041500            NaN
        1900-05-11      ...         -10.197333            NaN
        1900-05-12      ...                NaN            NaN
        1900-05-13      ...                NaN            NaN
        1900-05-14      ...                NaN            NaN
        1900-05-15      ...                NaN            NaN
        1900-05-16      ...                NaN            NaN
        1900-05-17      ...                NaN            NaN
        1900-05-18      ...                NaN            NaN
        1900-05-19      ...                NaN            NaN
        1900-05-20      ...                NaN            NaN
        1900-05-21      ...                NaN            NaN
        1900-05-22      ...                NaN            NaN
        1900-05-23      ...                NaN            NaN
        1900-05-24      ...                NaN            NaN
        1900-05-25      ...                NaN            NaN
        1900-05-26      ...                NaN            NaN
        1900-05-27      ...                NaN            NaN
        1900-05-28      ...                NaN            NaN
        1900-05-29      ...                NaN            NaN
        1900-05-30      ...                NaN            NaN
        1900-05-31      ...                NaN            NaN

                                                                  \
var1               appCat.utilities appCat.weather          call
id1     time4
AS14.01 1900-02-20              NaN            NaN -8.185332e-17
        1900-02-22              NaN            NaN           NaN
        1900-03-13              NaN            NaN -8.185332e-17
        1900-03-14              NaN            NaN -8.185332e-17
        1900-03-17              NaN            NaN           NaN
        1900-03-18              NaN            NaN           NaN
        1900-03-21              NaN            NaN -8.185332e-17
        1900-03-22              NaN            NaN -8.185332e-17
        1900-03-23        14.335000            NaN           NaN
        1900-03-24         3.528500            NaN           NaN
        1900-03-25        25.079500            NaN           NaN
        1900-03-26        -3.898350            NaN           NaN
        1900-03-27       -28.000500            NaN           NaN
        1900-03-28        -3.006968            NaN           NaN
        1900-03-29        -1.596650            NaN           NaN
        1900-03-30         4.375589            NaN           NaN
        1900-03-31         4.062150            NaN           NaN
        1900-04-01        -6.327830            NaN           NaN
        1900-04-02        -9.562148            NaN           NaN
        1900-04-03         4.482403            NaN -8.185332e-17
        1900-04-04        -2.556160            NaN -8.185332e-17
        1900-04-05        -5.718151            NaN           NaN
        1900-04-06        -0.421026            NaN           NaN
        1900-04-07        -0.324792            NaN           NaN
        1900-04-08        19.117708            NaN           NaN
        1900-04-09         4.410850            NaN -8.185332e-17
        1900-04-10        32.009525            NaN -8.185332e-17
        1900-04-11         3.553817            NaN           NaN
        1900-04-12       -45.811011            NaN           NaN
        1900-04-13              NaN            NaN           NaN
...                             ...            ...           ...
AS14.33 1900-05-02              NaN            NaN -8.185332e-17
        1900-05-03              NaN            NaN -8.185332e-17
        1900-05-04              NaN            NaN -8.185332e-17
        1900-05-05              NaN            NaN -8.185332e-17
        1900-05-06              NaN            NaN -8.185332e-17
        1900-05-07              NaN            NaN -8.185332e-17
        1900-05-08              NaN            NaN -8.185332e-17
        1900-05-09         1.351437            NaN           NaN
        1900-05-10         0.466125            NaN           NaN
        1900-05-11              NaN            NaN           NaN
        1900-05-12              NaN            NaN           NaN
        1900-05-13              NaN            NaN           NaN
        1900-05-14              NaN            NaN           NaN